<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="469" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
    <groups>
      <group name="smoke">
        <method signature="FirstDemo.div()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="div" class="tests.FirstDemo"/>
        <method signature="FirstDemo.mul()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="mul" class="tests.FirstDemo"/>
        <method signature="FirstDemo.sub()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="sub" class="tests.FirstDemo"/>
        <method signature="FirstDemo.sum()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="sum" class="tests.FirstDemo"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="FirstDemo.div()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="div" class="tests.FirstDemo"/>
        <method signature="FirstDemo.mul()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="mul" class="tests.FirstDemo"/>
        <method signature="FirstDemo.sub()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="sub" class="tests.FirstDemo"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Default test" duration-ms="469" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
      <class name="tests.FirstDemo">
        <test-method status="PASS" signature="div()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="div" duration-ms="46" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="PASS" signature="mul()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="mul" duration-ms="0" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method status="FAIL" signature="sub()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="sub" duration-ms="0" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [20]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at tests.FirstDemo.sub(FirstDemo.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method status="FAIL" signature="sum()[pri:0, instance:tests.FirstDemo@39aeed2f]" name="sum" duration-ms="0" started-at="2019-10-31T02:51:32Z" finished-at="2019-10-31T02:51:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [30] but found [40]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [30] but found [40]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at tests.FirstDemo.sum(FirstDemo.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
      </class> <!-- tests.FirstDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
